name: chess_app
description: Application d'échecs avec tutoriels, niveaux et jeu
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Logique des échecs
  chess: ^0.8.1

  # Gestion d'état — Riverpod
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0

  # Navigation
  go_router: ^13.2.0

  # Text to speech
  flutter_tts: ^4.0.2

  # Cache local
  shared_preferences: ^2.2.2

  # Utilitaires
  equatable: ^2.0.5
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.3.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/chess_club.png
    - assets/images/sans.png
    - assets/images/san.png