// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMaVkt6eD0ha6YtBgWPTahT8cTVctqEf0',
    appId: '1:1045191990822:web:ee93cb6e9e7c2d17fd50e7',
    messagingSenderId: '1045191990822',
    projectId: 'chessapp-2ffcc',
    authDomain: 'chessapp-2ffcc.firebaseapp.com',
    storageBucket: 'chessapp-2ffcc.firebasestorage.app',
    measurementId: 'G-B2TC0XM5JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlk5Q0h86NJjBHtuhxyBsmwCURpsl6X7M',
    appId: '1:1045191990822:android:e08201ce385cc48afd50e7',
    messagingSenderId: '1045191990822',
    projectId: 'chessapp-2ffcc',
    storageBucket: 'chessapp-2ffcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChGUt9gFjpsxbSENWZFc8LN9fiG0UcU6I',
    appId: '1:1045191990822:ios:a623d40b642484cefd50e7',
    messagingSenderId: '1045191990822',
    projectId: 'chessapp-2ffcc',
    storageBucket: 'chessapp-2ffcc.firebasestorage.app',
    iosBundleId: 'com.example.chessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChGUt9gFjpsxbSENWZFc8LN9fiG0UcU6I',
    appId: '1:1045191990822:ios:a623d40b642484cefd50e7',
    messagingSenderId: '1045191990822',
    projectId: 'chessapp-2ffcc',
    storageBucket: 'chessapp-2ffcc.firebasestorage.app',
    iosBundleId: 'com.example.chessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMaVkt6eD0ha6YtBgWPTahT8cTVctqEf0',
    appId: '1:1045191990822:web:b92a9c70b4c941befd50e7',
    messagingSenderId: '1045191990822',
    projectId: 'chessapp-2ffcc',
    authDomain: 'chessapp-2ffcc.firebaseapp.com',
    storageBucket: 'chessapp-2ffcc.firebasestorage.app',
    measurementId: 'G-GJQNQ0SEMJ',
  );
}
